export enum EventType {
    BALL_FIRST_COLLISION = 'BALL_FIRST_COLLISION',
    BALL_MERGED = 'BALL_MERGED',
    PLAYER_DROPPED_BALL = 'PLAYER_DROPPED_BALL',
    SCORE_CHANGED = 'SCORE_CHANGED',

    SETTINGS_BUTTON_CLICKED = 'SETTINGS_BUTTON_CLICKED',
    SETTINGS_PANEL_OPENED = 'SETTINGS_PANEL_OPENED',
    SETTINGS_PANEL_CLOSED = 'SETTINGS_PANEL_CLOSED'
};
